default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: bemind
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: aurora_development
  
test:
  <<: *default
  database: aurora_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: aurora_production
  username: aurora-project
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>